<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UacsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $data = [
            ['uacs_code' => '5020101000', 'account_title' => 'Traveling Expenses-Local', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020102000', 'account_title' => 'Traveling Expenses-Foreign', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020201001', 'account_title' => 'ICT Training Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020201002', 'account_title' => 'Training Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020202000', 'account_title' => 'Scholarship Grants/Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020301001', 'account_title' => 'ICT Office Supplies Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020301002', 'account_title' => 'Office Supplies Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020302000', 'account_title' => 'Accountable Forms Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020303000', 'account_title' => 'Non-Accountable Forms Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020304000', 'account_title' => 'Animal/Zoological Supplies Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020305000', 'account_title' => 'Food Supplies Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020306000', 'account_title' => 'Welfare Goods Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020307000', 'account_title' => 'Drugs and Medicines Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020308000', 'account_title' => 'Medical, Dental and Laboratory Supplies Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020309000', 'account_title' => 'Fuel, Oil and Lubricants Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020310000', 'account_title' => 'Agricultural and Marine Supplies Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020311001', 'account_title' => 'Textbooks and Instructional Materials Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020313000', 'account_title' => 'Chemical and Filtering Supplies Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321001', 'account_title' => 'Semi-Expendable Machinery', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321002', 'account_title' => 'Semi-Expendable-Office Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321003', 'account_title' => 'Semi-Expendable-Information and Communications Technology Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321004', 'account_title' => 'Semi-Expendable - Agricultural and Forestry Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321005', 'account_title' => 'Semi-Expendable - Marine and Fishery Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321006', 'account_title' => 'Semi-Expendable - Airport Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321007', 'account_title' => 'Semi-Expendable - Communication Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321008', 'account_title' => 'Semi-Expendable - Disaster Response and Rescue Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321009', 'account_title' => 'Semi-Expendable - Military, Police and Security Equipment Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321010', 'account_title' => 'Semi-Expendable - Medical Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321011', 'account_title' => 'Semi-Expendable - Printing Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321012', 'account_title' => 'Semi-Expendable - Sports Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321013', 'account_title' => 'Semi-Expendable - Technical and Scientific Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020321099', 'account_title' => 'Semi-Expendable - Other Machinery and Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020322000', 'account_title' => 'Semi-Expendable- Furniture, Fixtures and Books Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020322001', 'account_title' => 'Semi-Expendable - Furniture and Fixtures', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020322002', 'account_title' => 'Semi-Expendable - Books', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020399000', 'account_title' => 'Other Supplies and Materials Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020401000', 'account_title' => 'Water Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020402000', 'account_title' => 'Electricity Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020403000', 'account_title' => 'Gas/Heating Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020499000', 'account_title' => 'Other Utility Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020501000', 'account_title' => 'Postage and Courier Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020502001', 'account_title' => 'Telephone- Mobile', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020502002', 'account_title' => 'Telephone- Landline', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020503000', 'account_title' => 'Internet Subscription Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020504000', 'account_title' => 'Cable, Satellite, Telegraph and Radio Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020601001', 'account_title' => 'Awards/Rewards Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020601002', 'account_title' => 'Rewards and Incentives', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020602000', 'account_title' => 'Prizes', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020701001', 'account_title' => 'ICT Survey Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020701002', 'account_title' => 'Survey Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020702001', 'account_title' => 'ICT Research, Exploration and Development Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5020702002', 'account_title' => 'Research, Exploration and Development Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021001000', 'account_title' => 'Confidential Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021002000', 'account_title' => 'Intelligence Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021003000', 'account_title' => 'Extraordinary and Miscellaneous Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021101000', 'account_title' => 'Legal Services', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021102000', 'account_title' => 'Auditing Services', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021103001', 'account_title' => 'ICT Consultancy Services', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021103002', 'account_title' => 'Consultancy Services', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021199000', 'account_title' => 'Other Professional Services', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021201000', 'account_title' => 'Environment/Sanitary Services', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021202000', 'account_title' => 'Janitorial Services', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021203000', 'account_title' => 'Security Services', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021299099', 'account_title' => 'Other General Services', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021301000', 'account_title' => 'RM - Investment Property', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021302001', 'account_title' => 'RM - Aquaculture Structures', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021302002', 'account_title' => 'RM - Reforestation Projects', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021302099', 'account_title' => 'RM - Other Land Improvements', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021303001', 'account_title' => 'RM - Road Networks', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021303002', 'account_title' => 'RM - Flood Control Systems', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021303003', 'account_title' => 'RM - Sewer Systems', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021303004', 'account_title' => 'RM - Water Supply Systems', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021303005', 'account_title' => 'RM - Power Supply Systems', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021303006', 'account_title' => 'RM - Communication Networks', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021303007', 'account_title' => 'RM - Seaport Systems', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021303008', 'account_title' => 'RM - Airport Systems', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021303009', 'account_title' => 'RM - Parks, Plazas and Monuments', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021303010', 'account_title' => 'RM - Railway Systems', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021303099', 'account_title' => 'RM - Other Infrastructure Assets', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021304001', 'account_title' => 'RM - Buildings', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021304002', 'account_title' => 'RM - School Buildings', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021304003', 'account_title' => 'RM - Hospitals and Health Centers', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021304004', 'account_title' => 'RM - Markets', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021304005', 'account_title' => 'RM - Slaughterhouses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021304006', 'account_title' => 'RM - Hostels and Dormitories', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021304099', 'account_title' => 'RM - Other Structures', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305001', 'account_title' => 'RM - Machinery', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305002', 'account_title' => 'RM - Office Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305003', 'account_title' => 'RM - ICT Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305004', 'account_title' => 'RM -Agricultural and Forestry Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305005', 'account_title' => 'RM -Marine and Fishery Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305006', 'account_title' => 'RM - Airport Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305007', 'account_title' => 'RM - Communication Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305008', 'account_title' => 'RM - Construction and Heavy Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305009', 'account_title' => 'RM - Disaster Response and Rescue Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305010', 'account_title' => 'RM - Military, Police and Security Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305011', 'account_title' => 'RM - Medical Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305012', 'account_title' => 'RM - Printing Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305013', 'account_title' => 'RM - Sports Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305014', 'account_title' => 'RM - Technical and Scientific Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021305099', 'account_title' => 'RM - Other Machinery and Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021306001', 'account_title' => 'RM - Motor Vehicles', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021306002', 'account_title' => 'RM - Trains', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021306003', 'account_title' => 'RM - Aircrafts and Aircrafts Ground Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021306004', 'account_title' => 'RM - Watercrafts', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021306099', 'account_title' => 'RM - Other Transportation Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021307000', 'account_title' => 'RM - Furniture and Fixtures', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021308000', 'account_title' => 'RM - Repairs and Maintenance-Leased Assets', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021308001', 'account_title' => 'RM - Leased Assets, Buildings and other structures', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021308002', 'account_title' => 'RM - Leased Assets, Machinery and Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021308004', 'account_title' => 'RM - Leased Assets, ICT Machinery and Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021308003', 'account_title' => 'RM - Leased Assets, Transportation Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021308099', 'account_title' => 'RM - Leased Assets, Other Leased Assets', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021309001', 'account_title' => 'RM - Leased Assets Improvements, Land', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021309002', 'account_title' => 'RM - Leased Assets Improvements , Buildings', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021309099', 'account_title' => 'RM - Other Leased Assets Improvements', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021310001', 'account_title' => 'RM - Historical Buildings', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021310002', 'account_title' => 'RM - Work of Arts and Archeological Specimens', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021310099', 'account_title' => 'RM - Other Heritage Assets', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321001', 'account_title' => 'RM- Semi-Expendable - Machinery', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321002', 'account_title' => 'RM- Semi-Expendable - Office Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321003', 'account_title' => 'RM- Semi-Expendable - Information and Communication Technology Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321004', 'account_title' => 'RM- Semi-Expendable - Agricultural and Forestry Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321005', 'account_title' => 'RM- Semi-Expendable - Marine and Fishery Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321006', 'account_title' => 'RM - Airport Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321007', 'account_title' => 'RM- Semi-Expendable - Communication Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321008', 'account_title' => 'RM- Semi-Expendable - Disaster Response and Rescue Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321009', 'account_title' => 'RM- Semi-Expendable - Military Police and Security Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321010', 'account_title' => 'RM- Semi-Expendable - Medical Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321011', 'account_title' => 'RM- Semi-Expendable - Printing Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321012', 'account_title' => 'RM- Semi-Expendable - Sports Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321013', 'account_title' => 'RM- Semi-Expendable - Technical and Scientific Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021321099', 'account_title' => 'RM- Semi-Expendable - Other Machinery and Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021322001', 'account_title' => 'RM- Semi-Expendable - Furniture and Fixtures', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021322002', 'account_title' => 'RM- Semi-Expendable - Books', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021398000', 'account_title' => 'RM - Repairs and Maintenance-Others', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021399099', 'account_title' => 'RM - Other Property, Plant and Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021401000', 'account_title' => 'Subsidy to National Government Agencies', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021402000', 'account_title' => 'Assistance to Other National Government Agencies', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021403000', 'account_title' => 'Assistance to Local Government Units', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021404000', 'account_title' => 'Budgetary Support to Government-Owned or Controlled Corporations', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021404001', 'account_title' => 'Subsidy Support to Operations of GOCCs', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021405000', 'account_title' => 'Assistance to Non-Government Organizations/Civil Society Organizations', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021406000', 'account_title' => 'Internal Revenue Allotment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021407000', 'account_title' => 'Subsidy to Regional Offices/Staff Bureaus', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021408000', 'account_title' => 'Subsidy to Operating Units', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021409000', 'account_title' => 'Subsidy to Other Funds', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021499000', 'account_title' => 'Subsidies-Others', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021501001', 'account_title' => 'Taxes, Duties and Licenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021501002', 'account_title' => 'Tax Refund', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021502000', 'account_title' => 'Fidelity Bond Premiums', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021503000', 'account_title' => 'Insurance Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5021601000', 'account_title' => 'Labor and Wages', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029901000', 'account_title' => 'Advertising, Promotional and Marketing Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029902000', 'account_title' => 'Printing and Publication Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029903000', 'account_title' => 'Representation Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029904000', 'account_title' => 'Transportation and Delivery Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029905001', 'account_title' => 'Rents-Buildings and Structures', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029905002', 'account_title' => 'Rents-Land', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029905003', 'account_title' => 'Rents-Motor Vehicles', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029905004', 'account_title' => 'Rents-Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029905005', 'account_title' => 'Rents-Living Quarters', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029905006', 'account_title' => 'Operating Lease', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029905007', 'account_title' => 'Financial Lease', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029905008', 'account_title' => 'Rents–ICT Machinery and Equipment', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029906000', 'account_title' => 'Membership Dues and Contributions to Organizations', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029907001', 'account_title' => 'ICT Software Subscription', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029907002', 'account_title' => 'Data Center Service', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029907003', 'account_title' => 'Cloud Computing Service', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029907004', 'account_title' => 'Library and Other Reading Materials Subscription Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029907099', 'account_title' => 'Other Subscription Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029908000', 'account_title' => 'Donations', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029909000', 'account_title' => 'Litigation/Acquired Assets Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029910000', 'account_title' => 'Loss on Guaranty', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029921000', 'account_title' => 'Legal Defense Expense', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029922000', 'account_title' => 'Bank Transaction Fee', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029999001', 'account_title' => 'Website Maintenance', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5029999099', 'account_title' => 'Other Maintenance and Operating Expenses', 'allotment_class' => 'MOOE'],
            ['uacs_code' => '5010101001', 'account_title' => 'Basic Salary-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010102000', 'account_title' => 'Salaries and Wages-Casual/Contractual', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010201001', 'account_title' => 'PERA-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010202000', 'account_title' => 'Representation Allowance (RA)', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010203001', 'account_title' => 'Transportation Allowance (TA)', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010204001', 'account_title' => 'Clothing/Uniform Allowance-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010205003', 'account_title' => 'Subsistence Allowance-Magna Carta Benefits for Public Health Workers under R.A. 7305', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010206004', 'account_title' => 'Laundry Allowance-Magna Carta Benefits for Public Health Workers under R.A. 7305', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010207004', 'account_title' => 'Quarters Allowance-Magna Carta Benefits for Public Health Workers under R.A. 7305', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010208001', 'account_title' => 'Productivity Incentive Allowance - Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010210001', 'account_title' => 'Honoraria-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010211005', 'account_title' => 'HP-Magna Carta Benefits for Public Health Workers under R.A. 7305', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010212004', 'account_title' => 'Longevity Pay-Magna Carta Benefits for Public Health Workers under R.A. 7305', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010213001', 'account_title' => 'Overtime Pay', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010213002', 'account_title' => 'Night-shift Differential Pay', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010214001', 'account_title' => 'Year-End Bonus-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010215001', 'account_title' => 'Cash Gift-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010216001', 'account_title' => 'Mid-Year Bonus-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010299011', 'account_title' => 'Collective Negotiation Agreement Incentive-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010299012', 'account_title' => 'Productivity Enhancement Incentive-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010299014', 'account_title' => 'Performance Based Bonus-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010299038', 'account_title' => 'Anniversary Bonus–Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010301000', 'account_title' => 'Retirement and Life Insurance Premiums', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010302001', 'account_title' => 'Pag-IBIG-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010303001', 'account_title' => 'PhilHealth-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010304001', 'account_title' => 'ECIP-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010401001', 'account_title' => 'Pension Benefits-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010402001', 'account_title' => 'Retirement Gratuity-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010403001', 'account_title' => 'Terminal Leave Benefits-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010499001', 'account_title' => 'Lump-sum for Creation of New Positions-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010499003', 'account_title' => 'Lump-sum for Reclassification of Positions', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010499006', 'account_title' => 'Lump-sum for Compensation Adjustment', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010499007', 'account_title' => 'Lump-sum for Filling of Positions-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010499008', 'account_title' => 'Lump-sum for NBC No. 308', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010499009', 'account_title' => 'Lump-sum for Personnel Services', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010499010', 'account_title' => 'Lump-sum for Step Increments-Length of Service', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010499011', 'account_title' => 'Lump-sum for Step Increments-Meritorious Performance', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010499012', 'account_title' => 'Other Lump-sum', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010499015', 'account_title' => 'Loyalty Award-Civilian', 'allotment_class' => 'PS'],
            ['uacs_code' => '5010499099', 'account_title' => 'Other Personnel Benefits', 'allotment_class' => 'PS'],
            ['uacs_code' => '5030101000', 'account_title' => 'Management Supervision/ Trusteeship Fees', 'allotment_class' => 'FinEx'],
            ['uacs_code' => '5030102004', 'account_title' => 'Interest Expense - Others', 'allotment_class' => 'FinEx'],
            ['uacs_code' => '5030102001', 'account_title' => 'Interest Paid to Non Residents', 'allotment_class' => 'FinEx'],
            ['uacs_code' => '5030102002', 'account_title' => 'Interest Paid to Residents other than General Government', 'allotment_class' => 'FinEx'],
            ['uacs_code' => '5030102003', 'account_title' => 'Interest Paid to other General Government Units', 'allotment_class' => 'FinEx'],
            ['uacs_code' => '5030103000', 'account_title' => 'Guarantee Fees', 'allotment_class' => 'FinEx'],
            ['uacs_code' => '5030104000', 'account_title' => 'Bank Charges', 'allotment_class' => 'FinEx'],
            ['uacs_code' => '5030105000', 'account_title' => 'Commitment Fees', 'allotment_class' => 'FinEx'],
            ['uacs_code' => '5030199000', 'account_title' => 'Other Financial Charges', 'allotment_class' => 'FinEx'],
            ['uacs_code' => '5060301001', 'account_title' => 'Investment Property-Land', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060301002', 'account_title' => 'Investment Property-Buildings', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060401001', 'account_title' => 'Land', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060402001', 'account_title' => 'Aquaculture Structures', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060402002', 'account_title' => 'Reforestation Projects', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060402099', 'account_title' => 'Other Land Improvements', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060403001', 'account_title' => 'Road Networks', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060403002', 'account_title' => 'Flood Control Systems', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060403003', 'account_title' => 'Sewer Systems', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060403004', 'account_title' => 'Water Supply Systems', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060403005', 'account_title' => 'Power Supply Systems', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060403006', 'account_title' => 'Communication Networks', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060403007', 'account_title' => 'Seaport Systems', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060403008', 'account_title' => 'Airport Systems', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060403009', 'account_title' => "Parks, Plazas and Monuments", "allotment_class" =>'CO'],
            ['uacs_code' => "5060403099", "account_title" => 'Other Infrastructure Assets',"allotment_class" =>'CO'],
            ['uacs_code' => '5060404001', 'account_title' => 'Buildings', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060404002', 'account_title' => 'School Buildings', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060404003', 'account_title' => 'Hospitals and Health Centers', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060404006', 'account_title' => 'Hostels and Dormitories', 'allotment_class' => 'CO'],
            ['uacs_code' => "5060404099", "account_title" => "Other Structures", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405001", "account_title" => "Machinery", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405002", "account_title" => "Office Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405003", "account_title" => "Information and Communications Technology Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405004", "account_title" => "Agricultural and Forestry Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405005", "account_title" => "Marine and Fishery Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405006", "account_title" => "Airport Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405007", "account_title" => "Communications Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405008", "account_title" => "Construction and Heavy Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405009", "account_title" => "Disaster Response and Rescue Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405011", "account_title" => "Medical Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405012", "account_title" => "Printing Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405013", "account_title" => "Sports Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405014", "account_title" => "Technical and Scientific Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405015", "account_title" => "ICT Software", "allotment_class" =>'CO'],
            ['uacs_code' => "5060405099", "account_title" => "Other Machinery and Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => '5060406001', 'account_title' => 'Motor Vehicles', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060406002', 'account_title' => 'Trains', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060406003', 'account_title' => 'Aircrafts and Aircrafts Ground Equipment', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060406004', 'account_title' => 'Watercrafts', 'allotment_class' => 'CO'],
            ['uacs_code' => "5060406099", "account_title" => "Other Transportation Equipment", "allotment_class" =>'CO'],
            ['uacs_code' => '5060407001', 'account_title' => 'Furniture and Fixtures', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060407002', 'account_title' => 'Books', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060408001', 'account_title' => 'Historical Buildings', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060408002', 'account_title' => 'Works of Arts and Archeological Specimens', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060408099', 'account_title' => 'Other Heritage Assets', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060409001', 'account_title' => 'Work/Zoo Animals', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060409099', 'account_title' => 'Other Property, Plant and Equipment', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060601000', 'account_title' => 'Patents/Copyrights', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060602000', 'account_title' => 'Computer Software', 'allotment_class' => 'CO'],
            ['uacs_code' => '5060699000', 'account_title' => 'Other Intangible Assets', 'allotment_class' => 'CO'],

        ];

        foreach ($data as $item) {
            \App\Models\UacsCode::updateOrCreate(['uacs_code' => $item['uacs_code']], $item);
        }
    }
}
